Update MISC docs/lines to .NET 6
dotnet/upgrade-assistant pull request #965
Opened 2021-12-02 04:32 UTC by isaacrlevin

Updated MISC docs and Resources to say .NET 6. 

#959

2021-12-02 17:48 UTC, twsouthwick requested changes

2021-12-02 17:48 UTC, twsouthwick commented on docs/roadmap.md
> +  - [Choose between Current LTS (long-term servicing) .NET 6, Current (.NET 7) or Preview (.NET 7 Preview) for the target .NET version](https://github.com/dotnet/upgrade-assistant/issues/41)
Current LTS -> current LTS

Do we need "Current" before LTS?

2021-12-02 17:48 UTC, twsouthwick commented on src/extensions/default/analyzers/Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers/DefaultApiAlerts.apitargets
> +D: Although ClickOnce is supported on .NET 6+, apps do not have access to the System.Deployment.Application namespace. For more details see https://github.com/dotnet/deployment-tools/issues/27 and ht
It's supported on .NET 5+, so probably don't want this change

2021-12-02 17:48 UTC, twsouthwick commented on src/extensions/default/analyzers/Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers/Resources.resx
> +    <value>This type is not supported on .NET Core/.NET 6+ and should be replaced with a modern equivalent.</value>
Keep as .NET 5+ since that hasn't changed (one of the nice things of the '+')

2021-12-02 17:48 UTC, twsouthwick commented on src/extensions/default/analyzers/Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers/Resources.resx
> +    <value>This attribute type is not supported on .NET Core/.NET 6+ and should be replaced with a modern equivalent.</value>
same as above

2021-12-02 17:48 UTC, twsouthwick commented on src/extensions/default/analyzers/Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers/Resources.resx
> +    <value>This type is not supported on .NET Core/.NET 6+ and should be replaced with a modern equivalent.</value>
same as above

2021-12-02 21:51 UTC, isaacrlevin commented
@twsouthwick updated

2021-12-03 23:16 UTC, twsouthwick commented on docs/roadmap.md
> +  -	[Up front checks for technologies that might not be supported in 6+](https://github.com/dotnet/upgrade-assistant/blob/main/docs/design/Pre-UpgradeAnalysis.md#surface-unsupported-api-categories) o
```suggestion
  -	[Up front checks for technologies that might not be supported in .NET 6+](https://github.com/dotnet/upgrade-assistant/blob/main/docs/design/Pre-UpgradeAnalysis.md#surface-unsupported-api-categories) or could make the upgrade effort large in cost (links to docs, options available, best practices, etc.).
```

2021-12-03 23:16 UTC, twsouthwick commented on docs/roadmap.md
> +  - [Choose between LTS (long-term servicing) version (.NET 6), Latest Current (.NET 7) or Latest Preview (.NET 7 Preview) for the target .NET version](https://github.com/dotnet/upgrade-assistant/iss
```suggestion
  - [Choose between LTS (long-term servicing) version (.NET 6), Latest Current (.NET 6) or Latest Preview (.NET 6) for the target .NET version](https://github.com/dotnet/upgrade-assistant/issues/41)
```

.NET 7 doesn't have any preview version yet

2021-12-03 23:16 UTC, twsouthwick approved these changes
@isaacrlevin Thanks for the fixes! I updated a couple of missed values, but LGTM

2021-12-04 01:15 UTC, merged